image: public.ecr.aws/docker/library/ruby

stages:
  - test
  - publish

before_script:
  - "echo ':ssl_verify_mode: 0' >> ~/.gemrc"
  - bundle config ssl_verify_mode 0
  - bundle install --path=/tmp/bundler --jobs=8 --quiet

rubocop:
  stage: test
  image: public.ecr.aws/docker/library/ruby:3.4
  script:
    - bundle exec rubocop

rspec_latest:
  stage: test
  script:
    - bundle exec rspec

rspec_3.4:
  stage: test
  image: public.ecr.aws/docker/library/ruby:3.4
  script:
    - bundle exec rspec

rspec_3.3:
  stage: test
  image: public.ecr.aws/docker/library/ruby:3.3
  script:
    - bundle exec rspec

rspec_3.3:
  stage: test
  image: public.ecr.aws/docker/library/ruby:3.2
  script:
    - bundle exec rspec

rspec_3.1:
  stage: test
  image: public.ecr.aws/docker/library/ruby:3.1
  script:
    - bundle exec rspec

publish_gem:
  stage: publish
  script:
    - gem build access_token_agent.gemspec
    - gem push $(find `pwd` -name "access_token_agent-*.gem")
  only:
    - main
